version: '3'

services:
  postgres_db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: "1234abc"
    ports:
      - "5432:5432"
#     volumes:
#       - /srv/postgres:/var/lib/postgresql/data
  
  backend:
    image: andrezin10/back-incluwed:1.0.0
    environment:
      HOST: postgres_db
    ports:
      - 8080:8080
    links:
      - postgres_db
