name: Java CI with Maven e docker build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  maven:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Buildando imagem jar
      run: mvn clean package -DskipTests --file pom.xml
    - name: Gerando pasta target pro docker build
      uses: actions/upload-artifact@v3
      with:
        name: target
        path: target/
        
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v3
      with: 
        name: target
        path: target/
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Buildando imagem docker
      run: docker build . --file Dockerfile --tag andrezin10/back-incluwed:1.0.0
    - name: Docker push
      run: docker push ${{secrets.DOCKER_USER}}/back-incluwed:1.0.0
  
