name: Deploy [HOMOLOG]

on:
  push:
    branches:
      - main
jobs:
  vpn-and-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      
      - name: Install OpenVPN
        run: sudo apt-get update && sudo apt-get install -y openvpn
  
      - name: Setup VPN connection
        run: |
          echo "${{ secrets.VPN_USERNAME }}" > vpn_credentials.txt
          echo "${{ secrets.VPN_PASSWORD }}" >> vpn_credentials.txt
          sudo openvpn --config .github/workflows/config.ovpn --auth-user-pass vpn_credentials.txt --daemon
          sudo apt-get install telnet
          telnet 15.229.228.153 22
          # echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          # scp private_key -o StrictHostKeyChecking=no -i private_key dede@15.229.228.153:/home/dede
        env:
           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      # - name: SSH into the server
      #   run: |
      #     echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
      #     scp private_key -o StrictHostKeyChecking=no -i private_key dede@15.229.228.153:/home/dede
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
